FROM golang:1.26-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o upstream ./cmd/upstream

FROM scratch

WORKDIR /app

COPY --from=builder /src/upstream /app/upstream

EXPOSE 8081

ENTRYPOINT ["/app/upstream"]